import earth_science_geographic_information_science_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace earth_science_geographic_information_science_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end earth_science_geographic_information_science_theorem_canonical_lane_mathlib
end HautevilleHouse
